name: Build Kivy Android App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          ~/.buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('**/buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-
    
    - name: Update system packages
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y
    
    - name: Install Python and pip
      run: |
        sudo apt-get install -y python3-pip python3-dev
    
    - name: Install build dependencies
      run: |
        sudo apt-get install -y \
          build-essential \
          git \
          make \
          autoconf \
          automake \
          libtool \
          pkg-config \
          cmake \
          ninja-build \
          libasound2-dev \
          libpulse-dev \
          libaudio-dev \
          libjack-dev \
          libsndio-dev \
          libsamplerate0-dev \
          libx11-dev \
          libxext-dev \
          libxrandr-dev \
          libxcursor-dev \
          libxfixes-dev \
          libxi-dev \
          libxss-dev \
          libwayland-dev \
          libxkbcommon-dev \
          libdrm-dev \
          libgbm-dev \
          libgl1-mesa-dev \
          libgles2-mesa-dev \
          libegl1-mesa-dev \
          libdbus-1-dev \
          libibus-1.0-dev \
          libudev-dev \
          fcitx-libs-dev
    
    - name: Install Kivy dependencies
      run: |
        sudo add-apt-repository ppa:kivy-team/kivy -y
        sudo apt-get update
        sudo apt-get install -y python3-kivy
    
    - name: Fix Python externally-managed error
      run: |
        sudo rm -f /usr/lib/python*/EXTERNALLY-MANAGED
    
    - name: Install libtinfo5 for compatibility
      run: |
        wget http://launchpadlibrarian.net/371711898/libtinfo5_6.1-1ubuntu1.18.04_amd64.deb
        sudo dpkg -i libtinfo5_6.1-1ubuntu1.18.04_amd64.deb || true
        sudo apt-get install -f -y
    
    - name: Install additional build tools
      run: |
        sudo apt-get install -y \
          git \
          libssl-dev \
          cython3 \
          zip \
          unzip \
          openjdk-17-jdk \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          cmake \
          libffi-dev
    
    - name: Set up Java environment
      run: |
        echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV
        echo "/usr/lib/jvm/java-17-openjdk-amd64/bin" >> $GITHUB_PATH
    
    - name: Create buildozer directories
      run: |
        mkdir -p ~/.buildozer/android/platform
    
    - name: Install Python packages
      run: |
        python3 -m pip install --upgrade pip
        pip3 install --user --upgrade Cython==0.29.33 virtualenv
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    
    - name: Clone and install Buildozer
      run: |
        git clone https://github.com/kivy/buildozer.git
        cd buildozer
        python3 setup.py install --user
    
    - name: Verify Buildozer installation
      run: |
        buildozer --version
    
    - name: Initialize Buildozer (if buildozer.spec doesn't exist)
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi
    
    - name: Accept Android SDK licenses
      run: |
        mkdir -p ~/.buildozer/android/platform/android-sdk/licenses
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
        echo "d975f751698a77b662f1254ddbeed3901e976f5a" > ~/.buildozer/android/platform/android-sdk/licenses/intel-android-extra-license
    
    - name: Configure buildozer.spec for proper SDK/NDK versions
      run: |
        if [ -f buildozer.spec ]; then
          # Configure buildozer.spec with proper versions
          sed -i 's/#android.api = 28/android.api = 33/g' buildozer.spec
          sed -i 's/#android.minapi = 21/android.minapi = 21/g' buildozer.spec
          sed -i 's/#android.ndk = 23b/android.ndk = 25b/g' buildozer.spec
          sed -i 's/#android.accept_sdk_license = False/android.accept_sdk_license = True/g' buildozer.spec
          
          # Show buildozer.spec contents for debugging
          echo "=== buildozer.spec contents ==="
          cat buildozer.spec | grep -E "(android\.api|android\.minapi|android\.ndk|android\.accept_sdk_license)" || echo "No android settings found"
        fi
    
    - name: Download and setup Android SDK manually for Buildozer
      run: |
        # Download Android SDK command line tools
        cd ~/.buildozer/android/platform/
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools-linux-9477386_latest.zip
        
        # Create both new and old SDK structure for compatibility
        mkdir -p android-sdk/cmdline-tools
        mkdir -p android-sdk/tools/bin
        mv cmdline-tools android-sdk/cmdline-tools/latest
        
        # Create symlinks for backward compatibility
        ln -s ../../cmdline-tools/latest/bin/sdkmanager android-sdk/tools/bin/sdkmanager
        ln -s ../../cmdline-tools/latest/bin/avdmanager android-sdk/tools/bin/avdmanager
        
        # Set up SDK paths
        export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
        export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools
        
        # Install necessary components
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"
    
    - name: Build Android APK
      run: |
        # Set environment variables for buildozer
        export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
        export ANDROID_HOME=$ANDROID_SDK_ROOT
        export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/build-tools/33.0.2
        
        buildozer android debug
      env:
        BUILDOZER_LOG_LEVEL: 2
        JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
    
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: bin/*.apk
        retention-days: 30
    
    - name: Upload build logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          .buildozer/logs/
          *.log
        retention-days: 7
